name: Test release of action

on:
  pull_request:
    branches: '*'
  workflow_dispatch:

jobs:
  test_stale:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: rodvdka/git-sweep-merged-and-stale@v0.13-alpha
      - uses: rodvdka/git-sweep-merged-and-stale@v0.13-alpha
        with:
          action: "cleanup"
